services:
  mediawiki-bundle:
    image: ghcr.io/richie314/mediawiki-bundle
    restart: always
    volumes:
      - ./assets:/var/www/html/resources/assets:ro
      - ./upload:/var/www/html/images:rw
      # Comment the following line by addind a '#' at its start, uncomment by removing the '#'
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
    ports:
      - 80:80
    networks:
      db:
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
     - ./data:/var/lib/mysql
    networks:
      db:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "8080"
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      PMA_PORT: 3306 
      MYSQL_ROOT_PASSWORD: password
    networks:
      db:   
    depends_on:
      - mariadb 

networks:
  db:
    driver: bridge