services:
  mediawiki-bundle:
    image: mediawiki-bundle:latest
    restart: always
    volumes:
      - ./assets:/var/www/html/resources/assets:ro
      - ./upload:/var/www/html/images:rw
      # Comment the following line by addind a '#' at its start, uncomment by removing the '#'
      # - ./LocalSettings.php:/var/www/html/LocalSettings.php:ro
    ports:
      - 80:80
    networks:
      - db
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_wiki
    ports:
      - 5432:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -d mediacms -U mediacms"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 8080:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - db
    depends_on:
      - postgresql

networks:
  db:
    driver: bridge